"use client";

import { getRoadmapById } from "@/actions/roadmaps";
import ExpandCollapse from "@/components/flow-components/expand-collapse";
import { Separator } from "@/components/ui/separator";
import { useGenerateRoadmap } from "@/lib/queries";
import { decodeFromURL } from "@/lib/utils";
import { useQuery } from "@tanstack/react-query";
import { Loader2 } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { useShallow } from "zustand/react/shallow";
import { GeneratorControls } from "@/components/flow-components/generator-controls";
import { useUIStore } from "../../lib/stores/useUI";
import { useEffect, useRef, useState } from "react";

interface Props {
  roadmapId?: string;
}

export default function Roadmap({ roadmapId }: Props) {
  const { model, query, setQuery, modelApiKey } = useUIStore(
    useShallow((state) => ({
      model: state.model,
      query: state.query,
      setQuery: state.setQuery,
      modelApiKey: state.modelApiKey,
    })),
  );

  const params = useSearchParams();
  const hasAutoGenerated = useRef(false);
  const [timeoutError, setTimeoutError] = useState(false);
  
  // Handle topic query parameter from URL
  useEffect(() => {
    const topic = params.get('topic');
    console.log("🔍 URL topic:", topic);
    console.log("🔍 Current query:", query);
    if (topic && !query) {
      console.log("🔍 Setting query from URL topic:", topic);
      setQuery(topic);
    }
  }, [params, query, setQuery]);

  const { data: roadmap, isPending: isRoadmapPending } = useQuery({
    queryFn: async () => {
      if (!roadmapId) return null;
      let roadmap = await getRoadmapById(roadmapId);
      if (roadmap && roadmap.content) {
        try {
          let json = JSON.parse(roadmap.content);
          roadmap.content = json;
          return roadmap;
        } catch (error) {
          console.error("Error parsing roadmap content:", error);
          return roadmap;
        }
      }
      return roadmap;
    },
    queryKey: ["Roadmap", roadmapId],
    enabled: Boolean(roadmapId),
  });

  const { data, mutate, isPending, error } = useGenerateRoadmap(
    query,
    model,
    modelApiKey,
    {
      onSuccess: (response: any) => {
        console.log("✅ Roadmap generation successful:", response);
        setTimeoutError(false);
        if (response.status === true && response.tree) {
          console.log("✅ Tree data available:", response.tree);
        } else {
          console.error("❌ Invalid response format:", response);
        }
      },
      onError: (error: any) => {
        console.error("❌ Roadmap generation failed:", error);
        console.error("❌ Error details:", (error as any)?.response?.data);
        setTimeoutError(true);
        // Don't retry if it's an API key error
        if ((error as any)?.response?.data?.message?.includes("API key")) {
          console.log("🔑 API key error detected, not retrying");
        }
      },
      retry: (failureCount, error: any) => {
        console.log(`🔄 Retry attempt ${failureCount + 1}`);
        // Don't retry if it's an API key error
        if ((error as any)?.response?.data?.message?.includes("API key")) {
          return false;
        }
        // Retry up to 3 times for other errors
        return failureCount < 3;
      },
    }
  );

  // Auto-generate roadmap when query is set from URL
  useEffect(() => {
    const topic = params.get('topic');
    console.log("🔄 Auto-generation check:");
    console.log("  - Topic from URL:", topic);
    console.log("  - Current query:", query);
    console.log("  - Is pending:", isPending);
    console.log("  - Has data:", !!data);
    console.log("  - Has auto-generated:", hasAutoGenerated.current);
    
    // If we have a topic from URL and haven't auto-generated yet, trigger generation
    if (topic && !hasAutoGenerated.current && !isPending && !data) {
      hasAutoGenerated.current = true;
      console.log("🚀 Auto-generating roadmap for topic:", topic);
      setQuery(topic); // Set the query first
      // Use setTimeout to ensure the query is set before triggering mutation
      setTimeout(() => {
        mutate({
          body: { query: topic },
        });
      }, 100);
    }
  }, [params, query, isPending, data, mutate, setQuery]);

  // Reset auto-generation flag when query changes
  useEffect(() => {
    if (query !== params.get('topic')) {
      hasAutoGenerated.current = false;
      console.log("🔄 Reset auto-generation flag");
    }
  }, [query, params]);

  // Monitor loading state changes
  useEffect(() => {
    console.log("📊 State update:");
    console.log("  - isPending:", isPending);
    console.log("  - has data:", !!data);
    console.log("  - error:", error);
    if (!isPending && data) {
      console.log("✅ Roadmap generation completed successfully");
    }
  }, [isPending, data, error]);

  // Timeout handling - if loading for more than 30 seconds, show error
  useEffect(() => {
    let timeoutId: NodeJS.Timeout;
    if (isPending) {
      timeoutId = setTimeout(() => {
        console.log("⏰ Request timeout - showing error");
        setTimeoutError(true);
      }, 30000); // 30 seconds
    } else {
      setTimeoutError(false);
    }
    return () => {
      if (timeoutId) clearTimeout(timeoutId);
    };
  }, [isPending]);

  const roadmapData = roadmap?.content || data?.tree || decodeFromURL(params);
  const renderFlow = roadmapData?.[0]?.name || "";

  // Debug logging
  console.log("🔍 Final state:");
  console.log("  - Roadmap data:", roadmapData);
  console.log("  - API data:", data);
  console.log("  - Is pending:", isPending);
  console.log("  - Has roadmap data:", roadmapData && roadmapData.length > 0);
  console.log("  - Data status:", data?.status);
  console.log("  - Data tree:", data?.tree);
  console.log("  - Roadmap content:", roadmap?.content);
  console.log("  - Model API Key:", modelApiKey ? "SET" : "NOT SET");
  console.log("  - Model:", model);
  console.log("  - Error:", error);
  console.log("  - Timeout error:", timeoutError);

  return (
    <>
      <div className="mx-auto max-w-7xl">
        <GeneratorControls
          mutate={mutate}
          isPending={isPending}
          renderFlow={renderFlow}
          roadmapId={data?.roadmapId}
          dbRoadmapId={roadmapId || ""}
          visibility={roadmap?.visibility}
          title={query}
          key={roadmap?.visibility}
        />
      </div>
      <Separator />
      {isPending ? (
        <div className="h-[75vh] grid place-content-center">
          <div className="text-center">
            <Loader2 className="animate-spin w-8 h-8 mx-auto mb-4" />
            <p className="text-gray-600">Generating your roadmap...</p>
            {timeoutError && (
              <div className="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded-lg max-w-md mx-auto">
                <p className="text-sm text-yellow-600">
                  Taking longer than expected. Please wait or try again.
                </p>
              </div>
            )}
            {error && (
              <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg max-w-md mx-auto">
                <p className="text-sm text-red-600">
                  Error: {(error as any)?.response?.data?.message || (error as any)?.message || "Unknown error"}
                </p>
              </div>
            )}
          </div>
        </div>
      ) : isRoadmapPending && roadmapId ? (
        <div>
          <div className="h-[75vh] grid place-content-center">
            <Loader2 className="animate-spin w-8 h-8" />
          </div>
        </div>
      ) : (
        <>
          {roadmapData && roadmapData.length > 0 ? (
            <ExpandCollapse
              key={renderFlow}
              data={roadmapData}
              isPending={isRoadmapPending || isPending}
              roadmapId={roadmapId}
            />
          ) : (
            <div className="min-h-[75vh] flex items-center justify-center bg-gray-50">
              <div className="text-center max-w-md mx-auto">
                <div className="mb-8">
                  <h1 className="text-4xl font-bold text-gray-900 mb-4">
                    AI Roadmap Generator
                  </h1>
                </div>
                
                <div className="bg-white rounded-lg shadow-sm border p-6">
                  <div className="flex flex-col gap-4">
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 bg-purple-500 rounded-full"></div>
                      <p className="text-sm text-gray-600">
                        Your roadmap will appear here once generated
                      </p>
                    </div>
                    {data && !data.status && (
                      <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
                        <h3 className="text-sm font-semibold text-red-800 mb-2">
                          Roadmap Generation Failed
                        </h3>
                        <p className="text-sm text-red-600 mb-3">
                          {data.message || "Failed to generate roadmap"}
                        </p>
                        {data.message?.includes("API key") && (
                          <div className="mt-3 p-3 bg-yellow-50 border border-yellow-200 rounded">
                            <p className="text-sm text-yellow-800">
                              <strong>To fix this:</strong>
                            </p>
                            <ol className="text-sm text-yellow-700 mt-2 ml-4 list-decimal">
                              <li>Get a free API key from <a href="https://console.groq.com/" target="_blank" rel="noopener noreferrer" className="underline">Groq Console</a></li>
                              <li>Add it to your Vercel environment variables as <code>GROQ_API_KEY</code></li>
                              <li>Redeploy your application</li>
                            </ol>
                          </div>
                        )}
                      </div>
                    )}
                    {error && (
                      <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
                        <h3 className="text-sm font-semibold text-red-800 mb-2">
                          Generation Error
                        </h3>
                        <p className="text-sm text-red-600">
                          {(error as any)?.response?.data?.message || (error as any)?.message || "An error occurred during generation"}
                        </p>
                      </div>
                    )}
                    {params.get('topic') && !data && !isPending && (
                      <div className="mt-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                        <h3 className="text-sm font-semibold text-blue-800 mb-2">
                          Manual Generation
                        </h3>
                        <p className="text-sm text-blue-600 mb-3">
                          Auto-generation didn't trigger. Click the button below to generate the roadmap manually.
                        </p>
                        <button
                          onClick={() => {
                            const topic = params.get('topic');
                            if (topic) {
                              setQuery(topic);
                              mutate({
                                body: { query: topic },
                              });
                            }
                          }}
                          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                        >
                          Generate Roadmap for "{params.get('topic')}"
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}
        </>
      )}
    </>
  );
}
